### ISSUE TITLE
Boş 

### ISSUE THREAD

**Issue by ArviSlayer** [TheMacDeveloper/V14-Setup-Sistem-Register#1]

**Comment by TheMacDeveloper** [comment]
Sen önce git o dedin insanın alt yapısına bak sonra yan odaya bak annenle ilgilencem

**Comment by Bes-js** [comment]
![13_44_12_226173050-c9ccb6ed-aca8-4687-985f-1eaaba858ab7.png](https://github.com/TheMacDeveloper/V14-Setup-Sistem-Register/assets/89789101/cd678193-dd4a-4672-997b-01f65c607df9)

altyapıda bu ama nese :/

**Comment by ArviSlayer** [comment]
> Sen önce git o dedin insanın alt yapısına bak sonra yan odaya bak annenle ilgilencem

Anneci bücür 2, repoya girmeye hak kazandınız!

**Comment by TheMacDeveloper** [comment]
Boş
